-- SellerZone relational schema for Supabase.
-- Run this in Supabase SQL Editor before starting the migrated API.

create extension if not exists pgcrypto;

alter table public.products
  add column if not exists icon_key text not null default 'all',
  add column if not exists tag text not null default '',
  add column if not exists active boolean not null default true,
  add column if not exists stock integer not null default 0;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  balance numeric(12, 2) not null default 0,
  points integer not null default 0,
  frozen boolean not null default false,
  pix_key text not null default '',
  pix_name text not null default '',
  invite_code text unique,
  invited_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep an existing profiles table compatible when this schema is re-run.
alter table public.profiles
  add column if not exists pix_key text not null default '',
  add column if not exists pix_name text not null default '',
  add column if not exists invite_code text,
  add column if not exists invited_by text,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists profiles_invite_code_key
  on public.profiles (invite_code)
  where invite_code is not null;

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  qty integer not null default 1 check (qty > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  total numeric(12, 2) not null check (total >= 0),
  status text not null default 'placed',
  name text not null default '',
  email text not null default '',
  address text not null default '',
  city text not null default '',
  postal text not null default '',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  receipt text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null,
  reply text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table if not exists public.buybacks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id),
  qty integer not null default 1 check (qty > 0),
  price numeric(12, 2) not null check (price >= 0),
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.invite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  used_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.withdrawals enable row level security;
alter table public.deposits enable row level security;
alter table public.messages enable row level security;
alter table public.buybacks enable row level security;
alter table public.invite_codes enable row level security;
alter table public.settings enable row level security;

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
  for select using (active = true);

drop policy if exists profiles_self_access on public.profiles;
create policy profiles_self_access on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists cart_items_self_access on public.cart_items;
create policy cart_items_self_access on public.cart_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists orders_self_read on public.orders;
create policy orders_self_read on public.orders
  for select using (auth.uid() = user_id);

drop policy if exists withdrawals_self_access on public.withdrawals;
create policy withdrawals_self_access on public.withdrawals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists deposits_self_access on public.deposits;
create policy deposits_self_access on public.deposits
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists messages_self_access on public.messages;
create policy messages_self_access on public.messages
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists buybacks_self_access on public.buybacks;
create policy buybacks_self_access on public.buybacks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists invite_codes_public_read on public.invite_codes;
create policy invite_codes_public_read on public.invite_codes
  for select using (true);